### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by ameltom** [Code-Alchemy/AdMobAne#19]
It looks like parts of the native code are missing. For example:
getFunctions in ExtensionContext.java trying to call "new SetBirthYear()" but there is no SetBirthYear class.
AdMobBanner.java line 142 is not a legal code.
And there is many more missing things..

Can you please check it?
Thanks.

**Comment by Code-Alchemy** [comment]
Hello ameltom,

Thank you very much for point that out.

The source code has been checked and updated.
